<?php

$photos = ["http://ocha.smugmug.com/photos/i-JWt7W7S/0/M/i-JWt7W7S-M.jpg",
"http://ocha.smugmug.com/photos/i-xFHp7f7/0/M/i-xFHp7f7-M.jpg",
"http://ocha.smugmug.com/photos/i-Nr3FmD5/0/M/i-Nr3FmD5-M.jpg",
"http://ocha.smugmug.com/photos/i-gvsJ225/0/M/i-gvsJ225-M.jpg",
"http://ocha.smugmug.com/photos/i-BdPxsNz/0/M/i-BdPxsNz-M.jpg",
"http://ocha.smugmug.com/photos/i-9DWXm7q/0/M/i-9DWXm7q-M.jpg",
"http://ocha.smugmug.com/photos/i-rppMLvC/0/M/i-rppMLvC-M.jpg",
"http://ocha.smugmug.com/photos/i-GH4BvRt/0/M/i-GH4BvRt-M.jpg",
"http://ocha.smugmug.com/photos/i-QSN9BQP/0/M/i-QSN9BQP-M.jpg",
"http://ocha.smugmug.com/photos/i-LR2bVP5/0/M/i-LR2bVP5-M.jpg",
"http://ocha.smugmug.com/photos/i-x5fVTMn/0/M/i-x5fVTMn-M.jpg",
"http://ocha.smugmug.com/photos/i-b2DzS3C/0/M/i-b2DzS3C-M.jpg",
"http://ocha.smugmug.com/photos/i-kfTZJXJ/0/M/i-kfTZJXJ-M.jpg",
"http://ocha.smugmug.com/photos/i-GgS3CSx/0/M/i-GgS3CSx-M.jpg",
"http://ocha.smugmug.com/photos/i-6JmthQg/0/M/i-6JmthQg-M.jpg",
"http://ocha.smugmug.com/photos/i-phRdDGB/0/M/i-phRdDGB-M.jpg"];

?>
